name: highchartjs
description: "A wrapper implementation for Highcharts.js"
version: 0.0.2
homepage: https://github.com/iamarifdev/highchartjs
repository: https://github.com/iamarifdev/highchartjs

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.0
  url_launcher: ^6.3.0
  web: ^1.1.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.precisiondatalab.highchartjs
        pluginClass: HighChartPlugin
      ios:
        pluginClass: HighChartPlugin
      macos:
        pluginClass: HighChartPlugin
      web:
        pluginClass: HighChartPlatformInterface
        fileName: highchartjs_web.dart
